joint_1: #AX-12A
  ID: 1
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Moving_Speed: 50

joint_2: #MX-28T
  ID: 2
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 4095
  Moving_Speed: 50

joint_3: #AX-18A
  ID: 3
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Moving_Speed: 50

joint_4: #AX-18A
  ID: 4
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Moving_Speed: 50

joint_5: #AX-12A
  ID: 5
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Moving_Speed: 50

joint_6: #AX-12A
  ID: 6
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Moving_Speed: 50
